version: '3.8'

services:
  video-processor:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./outputs:/app/outputs
      - ./temp:/app/temp
    environment:
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - OUTPUT_DIR=/app/outputs
      - TEMP_DIR=/app/temp
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3 